// <auto-generated />
using System;
using Jadlify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jadlify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JadlifyDbContext))]
    [Migration("20260721121753_MealPlanEntrySourceAndProductSnapshot")]
    partial class MealPlanEntrySourceAndProductSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jadlify.Domain.Planning.DailyMacroGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("daily_macro_goals", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Planning.MealPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_type");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("meal_plan_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_plan_entries_exactly_one_source", "quantity > 0 AND (\n    (source = 'Recipe' AND recipe_id IS NOT NULL AND product_id IS NULL)\n    OR (source = 'Product' AND recipe_id IS NULL AND product_id IS NOT NULL)\n)");
                        });
                });

            modelBuilder.Entity("Jadlify.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("PackageSizeGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("package_size_grams");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Barcode");

                    b.HasIndex("UserId", "Category", "Name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Portions")
                        .HasColumnType("integer")
                        .HasColumnName("portions");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Planning.DailyMacroGoal", b =>
                {
                    b.OwnsOne("Jadlify.Domain.Nutrition.MacroNutrients", "Target", b1 =>
                        {
                            b1.Property<Guid>("DailyMacroGoalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_calories");

                            b1.Property<decimal>("Carbohydrates")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_carbohydrates");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_fat");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_protein");

                            b1.HasKey("DailyMacroGoalId");

                            b1.ToTable("daily_macro_goals");

                            b1.WithOwner()
                                .HasForeignKey("DailyMacroGoalId");
                        });

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Jadlify.Domain.Planning.MealPlanEntry", b =>
                {
                    b.HasOne("Jadlify.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Jadlify.Domain.Planning.PlannedProductSnapshot", "Product", b1 =>
                        {
                            b1.Property<Guid>("MealPlanEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("product_category");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("product_name");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("MealPlanEntryId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("meal_plan_entries");

                            b1.WithOwner()
                                .HasForeignKey("MealPlanEntryId");

                            b1.OwnsOne("Jadlify.Domain.Nutrition.MacroNutrients", "Per100Grams", b2 =>
                                {
                                    b2.Property<Guid>("PlannedProductSnapshotMealPlanEntryId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Calories")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("product_calories_per_100g");

                                    b2.Property<decimal>("Carbohydrates")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("product_carbohydrates_per_100g");

                                    b2.Property<decimal>("Fat")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("product_fat_per_100g");

                                    b2.Property<decimal>("Protein")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("product_protein_per_100g");

                                    b2.HasKey("PlannedProductSnapshotMealPlanEntryId");

                                    b2.ToTable("meal_plan_entries");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedProductSnapshotMealPlanEntryId");
                                });

                            b1.Navigation("Per100Grams")
                                .IsRequired();
                        });

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Jadlify.Domain.Products.Product", b =>
                {
                    b.OwnsOne("Jadlify.Domain.Nutrition.NutritionFacts", "Details", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Calcium")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("calcium_per_100g");

                            b1.Property<decimal?>("Fiber")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("fiber_per_100g");

                            b1.Property<decimal?>("Iron")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("iron_per_100g");

                            b1.Property<decimal?>("MonounsaturatedFat")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("monounsaturated_fat_per_100g");

                            b1.Property<decimal?>("PolyunsaturatedFat")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("polyunsaturated_fat_per_100g");

                            b1.Property<decimal?>("Potassium")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("potassium_per_100g");

                            b1.Property<decimal?>("Salt")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("salt_per_100g");

                            b1.Property<decimal?>("SaturatedFat")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("saturated_fat_per_100g");

                            b1.Property<decimal?>("Sodium")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("sodium_per_100g");

                            b1.Property<decimal?>("Sugars")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("sugars_per_100g");

                            b1.Property<decimal?>("TransFat")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("trans_fat_per_100g");

                            b1.Property<decimal?>("VitaminA")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("vitamin_a_per_100g");

                            b1.Property<decimal?>("VitaminC")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("vitamin_c_per_100g");

                            b1.Property<decimal?>("VitaminD")
                                .HasPrecision(12, 6)
                                .HasColumnType("numeric(12,6)")
                                .HasColumnName("vitamin_d_per_100g");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Jadlify.Domain.Nutrition.MacroNutrients", "Per100Grams", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("calories_per_100g");

                            b1.Property<decimal>("Carbohydrates")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("carbohydrates_per_100g");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("fat_per_100g");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("protein_per_100g");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Per100Grams")
                        .IsRequired();
                });

            modelBuilder.Entity("Jadlify.Domain.Recipes.Recipe", b =>
                {
                    b.OwnsMany("Jadlify.Domain.Recipes.RecipeIngredient", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid")
                                .HasColumnName("recipe_id");

                            b1.Property<Guid>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("product_name");

                            b1.HasKey("RecipeId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("recipe_ingredients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsOne("Jadlify.Domain.Nutrition.GramAmount", "WholeRecipeAmount", b2 =>
                                {
                                    b2.Property<Guid>("RecipeIngredientRecipeId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RecipeIngredientProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("whole_recipe_grams");

                                    b2.HasKey("RecipeIngredientRecipeId", "RecipeIngredientProductId");

                                    b2.ToTable("recipe_ingredients");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeIngredientRecipeId", "RecipeIngredientProductId");
                                });

                            b1.OwnsOne("Jadlify.Domain.Nutrition.MacroNutrients", "Per100Grams", b2 =>
                                {
                                    b2.Property<Guid>("RecipeIngredientRecipeId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RecipeIngredientProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Calories")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("calories_per_100g");

                                    b2.Property<decimal>("Carbohydrates")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("carbohydrates_per_100g");

                                    b2.Property<decimal>("Fat")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("fat_per_100g");

                                    b2.Property<decimal>("Protein")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("protein_per_100g");

                                    b2.HasKey("RecipeIngredientRecipeId", "RecipeIngredientProductId");

                                    b2.ToTable("recipe_ingredients");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeIngredientRecipeId", "RecipeIngredientProductId");
                                });

                            b1.Navigation("Per100Grams")
                                .IsRequired();

                            b1.Navigation("WholeRecipeAmount")
                                .IsRequired();
                        });

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
