// <auto-generated />
using System;
using Jadlify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jadlify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JadlifyDbContext))]
    partial class JadlifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jadlify.Domain.Planning.DailyMacroGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("daily_macro_goals", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Planning.MealPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_type");

                    b.Property<int>("Portions")
                        .HasColumnType("integer")
                        .HasColumnName("portions");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("meal_plan_entries", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Barcode");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Portions")
                        .HasColumnType("integer")
                        .HasColumnName("portions");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Jadlify.Domain.Planning.DailyMacroGoal", b =>
                {
                    b.OwnsOne("Jadlify.Domain.Nutrition.MacroNutrients", "Target", b1 =>
                        {
                            b1.Property<Guid>("DailyMacroGoalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_calories");

                            b1.Property<decimal>("Carbohydrates")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_carbohydrates");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_fat");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("target_protein");

                            b1.HasKey("DailyMacroGoalId");

                            b1.ToTable("daily_macro_goals");

                            b1.WithOwner()
                                .HasForeignKey("DailyMacroGoalId");
                        });

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Jadlify.Domain.Planning.MealPlanEntry", b =>
                {
                    b.HasOne("Jadlify.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jadlify.Domain.Products.Product", b =>
                {
                    b.OwnsOne("Jadlify.Domain.Nutrition.MacroNutrients", "Per100Grams", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("calories_per_100g");

                            b1.Property<decimal>("Carbohydrates")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("carbohydrates_per_100g");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("fat_per_100g");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("protein_per_100g");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Per100Grams")
                        .IsRequired();
                });

            modelBuilder.Entity("Jadlify.Domain.Recipes.Recipe", b =>
                {
                    b.OwnsMany("Jadlify.Domain.Recipes.RecipeIngredient", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid")
                                .HasColumnName("recipe_id");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("RecipeId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("recipe_ingredients", (string)null);

                            b1.HasOne("Jadlify.Domain.Products.Product", null)
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsOne("Jadlify.Domain.Nutrition.GramAmount", "WholeRecipeAmount", b2 =>
                                {
                                    b2.Property<Guid>("RecipeIngredientRecipeId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RecipeIngredientProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("whole_recipe_grams");

                                    b2.HasKey("RecipeIngredientRecipeId", "RecipeIngredientProductId");

                                    b2.ToTable("recipe_ingredients");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeIngredientRecipeId", "RecipeIngredientProductId");
                                });

                            b1.Navigation("WholeRecipeAmount")
                                .IsRequired();
                        });

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
